# Generated by Django 4.1.2 on 2022-10-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Department")),
                ("parent_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="Middle name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                (
                    "employment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Employment date"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="Salary"
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.department",
                    ),
                ),
            ],
        ),
    ]
